version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    depends_on:
      - mysql
    restart: always
    networks:
      - app-network

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./.data/db:/var/lib/mysql"
    networks:
      - app-network
    ports:
      - "3306:3306"
    restart: always

networks:
  app-network:
    driver: bridge


